// TEKODA TYPES
export const FETCH_LIST_RESTAURANT_REQUEST = "FETCH_LIST_RESTAURANT_REQUEST";
export const FETCH_LIST_RESTAURANT_SUCCEEDED = "FETCH_LIST_RESTAURANT_SUCCEEDED";

export const GET_RESTAURANT_SEARCH_DETAIL_REQUEST = "GET_RESTAURANT_SEARCH_DETAIL_REQUEST";
export const GET_RESTAURANT_SEARCH_DETAIL_SUCCEEDED = "GET_RESTAURANT_SEARCH_DETAIL_SUCCEEDED";

export const REMOVE_RESTAURANT_SEARCH_DETAIL = "REMOVE_RESTAURANT_SEARCH_DETAIL";

export const SEND_SURVEY_FORM_REQUEST = "SEND_SURVEY_FORM_REQUEST";
export const SEND_SURVEY_FORM_SUCCEEDED = "SEND_SURVEY_FORM_SUCCEEDED";

// AUTH TYPES
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCEEDED = "USER_REGISTER_SUCCEEDED";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";

export const CHECK_AUTHENTICATED_REQUEST = "CHECK_AUTHENTICATED_REQUEST";
export const CHECK_AUTHENTICATED_SUCCEEDED = "CHECK_AUTHENTICATED_SUCCEEDED";
export const CHECK_AUTHENTICATED_FAILED = "CHECK_AUTHENTICATED_FAILED";

// UTIL TYPES
export const LOADING_UI = "LOADING_UI";
export const LOADED_UI = "LOADED_UI";

// ERROR TYPES
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
