// TEKODA TYPES
export const FETCH_LIST_RESTAURANT_REQUEST = "FETCH_LIST_RESTAURANT_REQUEST";
export const FETCH_LIST_RESTAURANT_SUCCEEDED = "FETCH_LIST_RESTAURANT_SUCCEEDED";

export const FETCH_LIST_RESTAURANT_PER_PAGE_REQUEST = "FETCH_LIST_RESTAURANT_PER_PAGE_REQUEST";
export const FETCH_LIST_RESTAURANT_PER_PAGE_SUCCEEDED = "FETCH_LIST_RESTAURANT_PER_PAGE_SUCCEEDED";

export const GET_RESTAURANT_SEARCH_DETAIL_REQUEST = "GET_RESTAURANT_SEARCH_DETAIL_REQUEST";
export const GET_RESTAURANT_SEARCH_DETAIL_SUCCEEDED = "GET_RESTAURANT_SEARCH_DETAIL_SUCCEEDED";

export const GET_RESTAURANT_BY_ID = "GET_RESTAURANT_BY_ID";

export const REMOVE_RESTAURANT_SEARCH_DETAIL = "REMOVE_RESTAURANT_SEARCH_DETAIL";

export const SEND_SURVEY_FORM_REQUEST = "SEND_SURVEY_FORM_REQUEST";
export const SEND_SURVEY_FORM_SUCCEEDED = "SEND_SURVEY_FORM_SUCCEEDED";

export const SEARCH_RESTAURANT_REQUEST = "SEARCH_RESTAURANT_REQUEST";
export const SEARCH_RESTAURANT_SUCCEEDED = "SEARCH_RESTAURANT_SUCCEEDED";

// AUTH TYPES
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCEEDED = "REGISTER_USER_SUCCEEDED";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";

export const CHECK_AUTHENTICATED_REQUEST = "CHECK_AUTHENTICATED_REQUEST";
export const CHECK_AUTHENTICATED_SUCCEEDED = "CHECK_AUTHENTICATED_SUCCEEDED";
export const CHECK_AUTHENTICATED_FAILED = "CHECK_AUTHENTICATED_FAILED";

// UTIL TYPES
export const LOADING_UI = "LOADING_UI";
export const LOADED_UI = "LOADED_UI";

// ERROR TYPES
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SHOW_ACTIVE = "SHOW_ACTIVE";
export const END_ACTIVE = "END_ACTIVE";
